"""Bedrock semantic reasoning contracts.

Hard boundary: the model receives deterministic artifacts and documentation, and returns
*judgements and prose*. It never returns a metric, a statistic, a ranking, or an action that
mutates the experiment. Every field here is validated before the artifact is stored.
"""

from datetime import datetime

from pydantic import Field

from ml_engine.contracts.common import RecommendedAction, Severity, StrictModel

REASONING_SCHEMA_VERSION = "1.0"


class SemanticLeakageFinding(StrictModel):
    feature: str
    severity: Severity
    confidence: str = Field(description="low | medium | high — the model's own qualifier.")
    reasoning: str = Field(description="Why this feature may not be available at prediction time.")
    recommended_action: RecommendedAction = RecommendedAction.REVIEW
    evidence_basis: list[str] = Field(
        default_factory=list,
        description="Which deterministic inputs or documentation fields the judgement rests on.",
    )


class FeatureInterpretation(StrictModel):
    feature: str
    interpretation: str
    concern: str | None = None


class DataQualityConcern(StrictModel):
    topic: str
    severity: Severity
    explanation: str
    affected_columns: list[str] = Field(default_factory=list)


class ProposedExperiment(StrictModel):
    """A proposal only. A human starts the next experiment in v1.0."""

    title: str
    hypothesis: str
    proposed_changes: list[str] = Field(default_factory=list)
    expected_insight: str
    priority: str = Field(default="medium", description="low | medium | high")


class ReasoningReport(StrictModel):
    schema_version: str = REASONING_SCHEMA_VERSION
    experiment_id: str
    generated_at: datetime
    model_id: str = Field(description="Bedrock model identifier used for this analysis.")
    input_artifacts: list[str] = Field(
        default_factory=list, description="Artifact keys supplied as context."
    )
    executive_summary: str
    semantic_leakage: list[SemanticLeakageFinding] = Field(default_factory=list)
    feature_interpretations: list[FeatureInterpretation] = Field(default_factory=list)
    data_quality_concerns: list[DataQualityConcern] = Field(default_factory=list)
    model_behaviour_narrative: str | None = None
    assumptions: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    proposed_experiments: list[ProposedExperiment] = Field(default_factory=list)
    disclaimer: str = (
        "Generated by a language model from deterministic outputs. It contains no computed "
        "statistics and never modifies experiment results or feature selection."
    )
